<?php 

unset($_SESSION['E_JOUR']);
unset($_SESSION['E_MOIS']);
unset($_SESSION['E_ANNEE']);
unset($_SESSION['E_JOUR_MOIS_ANNEE']);
unset($_SESSION['E_ANIMAL']);
unset($_SESSION['E_USER']);
unset($_SESSION['E_ADD_USER']);
unset($_SESSION['E_USER_SUPP']);
unset($_SESSION['E_RESERVATION']);
unset($_SESSION['E_ANIMAL']);
unset($_SESSION['E_ANIMAL_EXIST']);
unset($_SESSION['E_CONNEXION']);
unset($_SESSION['E_CONNEXION_REQUIS']);
unset($_SESSION['E_RESERVATION_MODIFIER']);
unset($_SESSION['E_DATE_FIN']);
unset($_SESSION['E_DATE_DEBUT']);
unset($_SESSION['E_DATE_DEBUT_SAISON']);
unset($_SESSION['E_DATE_FIN_SAISON']);
unset($_SESSION['E_DATE_DEBUT_BLA']);
unset($_SESSION['E_DATE_FIN_BLA']);
unset($_SESSION['E_DATE_DEBUT_BLE']);
unset($_SESSION['E_DATE_FIN_BLE']);
unset($_SESSION['E_DATE_DEBUT_ROU']);
unset($_SESSION['E_DATE_FIN_ROU']);
unset($_SESSION['E_PRIX_BLA']);
unset($_SESSION['E_PRIX_BLE']);
unset($_SESSION['E_PRIX_ROU']);
unset($_SESSION['E_TARIFS']);
unset($_SESSION['E_TARIFS_EXISTANTS']);



unset($_SESSION['V_USER']);
unset($_SESSION['V_ADD_USER']);
unset($_SESSION['V_USER_SUPP']);
unset($_SESSION['V_ANIMAL']);
unset($_SESSION['V_SUPP_ANIMAL']);
unset($_SESSION['V_ADD_ANIMAL']);
unset($_SESSION['V_RESERVATION_MODIFIER']);
unset($_SESSION['V_ADD_RESERVATION']);
unset($_SESSION['V_ETAT']);
unset($_SESSION['V_SUPP_RESERVATION']);
unset($_SESSION['V_CONNEXION']);
unset($_SESSION['V_TARIFS']);
unset($_SESSION['V_TARIFS_SUPP']);
unset($_SESSION['V_MESSAGE']);
unset($_SESSION['V_SUPP_MESSAGE']);
unset($_SESSION['V_MODIFIER_MESSAGE']);

?>

